First version for updating DVV-data
GispoCoding/jkr-core pull request #44
Opened 2023-04-12 09:15 UTC by Mtk112

First version for updating DVV-data.

2023-04-12 14:50 UTC, Rikuoja requested changes
Hyvin etenee! Huomasin vain kaikenlaisia juttuja joita en ollut ehtinyt vielä miettiä ollenkaan, niin kommenteissa korjausehdotuksia ja mietittävää myös seuraavalle sprintille :)

2023-04-12 14:50 UTC, Rikuoja commented on scripts/import_dvv.sql
> +-- This will set loppupvm to all previous owners of the building, even if only one changed...
Tätä ei luultavasti voi tehdä vain insert-triggerillä, koska useita omistajia voi olla edelleen.

Tässähän käy myös niin, että jos rakennuksella on useampi omistaja, uuden omistajan lisääminen aina poistaa edellisen, ja lisäksi laittaa loppupäiväksi alkupäivän - 1 päivä. Se ei luultavasti onnistu, koska loppupäivämäärä ei voi olla ennen alkupäivämäärää.

Eli pitää miettiä poistuvien omistajien päivitys omana vaiheenaan ehkä ennen omistajien lisäämistä.

Eli 
1) jos tietokannassa on on jkr.rakennuksen_omistajat-taulussa olemassa osapuolia, joita ei enää löydy omistajista eli jkr_dvv.omistajat-taulusta,  asetetaan näille ennen omistajien tuontia loppupäivämäärä. Käytetään näiden hakuun siis joko a) henkilötunnus, b) dvv-tiedontuottaja + y-tunnus tai näiden puuttuessa c) nimi, osoite ja kaikki muut rivit, eli samalla tavalla kuin uusia osapuolia luotaessa rivillä https://github.com/GispoCoding/jkr-core/blob/main/scripts/import_dvv.sql#L103

2) Sen jälkeen tuodaan uudet omistajat jkr_dvv.omistajat-taulusta (samat kolme vaihetta a), b) ja c) kuin ennenkin), ja jos omistaja on jo olemassa, päivitetään vain muuttuneet tiedot.

2023-04-12 14:50 UTC, Rikuoja commented on scripts/import_dvv.sql
> +-- This will set loppupvm to all previous owners of the building, even if only one changed...
Tai siis, ton vanhojen omistajien tarkistamisen ja loppupäivämäärien merkitsemisen rakennuksen_omistajat-tauluun voi tehdä myös uusien osapuolten lisäämisen jälkeen.

Mutta se pitää tehdä ennen kuin insertataan mitään rakennuksen_omistajat-tauluun, eli ehkä jkr.osapuoli-insert- ja jkr.rakennuksen_omistajat-insert-vaiheiden välissä?

2023-04-12 14:50 UTC, Rikuoja commented on scripts/import_dvv.sql
> +-- poistetaan vanhat osoitteet. How to determine which addresses are old?
Annetaan katujen olla toistaiseksi. Vanhoista kaduista ei ole haittaa, poistetaan vain vanhat osoitteet näille kaduille.

2023-04-12 14:50 UTC, Rikuoja commented on scripts/import_dvv.sql
> +-- Add ytunnus as unique constraint? Otherwise there is no unique or exclusion constraint. Function?
Itse asiassa tuolla on ytunnus-unique-constraint, mutta se vaatii lisäehdon "tiedontuottajatunnus" ="dvv". Sen takia constraint löytyy unique indeksinä
```
"uidx_osapuoli_ytunnus_dvv" UNIQUE, btree (ytunnus) WHERE tiedontuottaja_tunnus = 'dvv'::text
 ```
 
 Johtuu siitä, että muilta tiedontuottajilta voi kuljetustietojen yhteydessä tulla lisää osapuolia joilla on sama ytunnus. Mutta dvv-osapuolille ytunnus on aina unique.

2023-04-12 14:50 UTC, Rikuoja commented on scripts/import_dvv.sql
> +-- What do we want to do with updating the alkupvm? Keep only the oldest alkupvm?
Ehkä tässä voisi esimerkiksi katsoa kumpi päivämääristä on aikaisempi. Mutta ei ole välttämätöntä päivittää alkupäivämäärää, jos sama henkilö on omistanut rakennuksen aiemminkin, luultavasti tässä on kyseessä vain tiedon korjaus, eikä voida tietää mikä näistä riveistä sisältää oikean alkupäivämäärän ja mikä väärän alkupäivämäärän.

2023-04-12 14:50 UTC, Rikuoja commented on scripts/import_dvv.sql
> +create or replace function update_osapuoli_without_henkilotunnus() returns void as $$
Voi olla että tämä funktio pitää jättää käyttämättä, koska on periaatteessa mahdollista, ettei kyseessä ole sama henkilö. On turvallisempaa luoda aina henkilötunnukselliset henkilöt uusina osapuolina, ja pitää henkilötunnuksettomat henkilötunnuksettomina, jottei henkilötunnukselle jää merkintää omistuksesta, joka on ollut ilman henkilötunnusta.

Ei siis haittaa, vaikka kohteen omistajissa olisi useita samannimisiä osapuolia eri aikoina. Näin käy joka tapauksessa hyvin usein, koska omistajien nimiä/osoitteita kirjoitetaan eri tavalla. Käytännössä kyseessä on ulkomainen omistaja.

2023-04-12 14:50 UTC, Rikuoja commented on scripts/import_dvv.sql
> +select update_osapuoli_without_henkilotunnus();
Tämän funktion sijasta voisi itse asiassa lisätä funktion update_osapuoli_with_ytunnus(), joka päivittää kaikki ne osapuolet, joilla on "tiedontuottaja_tunnus" dvv ja tunnettu y-tunnus.

Niitä ei voi olla useampia, eli ne pitää päivittää; kyseessä omistajayrityksen/yhteisön yhteystiedot. Tiedontuottaja_tunnus dvv pitää vaan aina muistaa tarkistaa.

2023-04-12 14:50 UTC, Rikuoja commented on scripts/import_dvv.sql
> +-- Updates the person's information, if new insert conflicts with existing one.
Niin joo, itse asiassa tähän voisi myös laittaa lisäehdon "tiedontuottaja_tunnus" = dvv, siltä varalta että jostain muista lähteistä tulee tulevaisuudessa myös henkilötunnuksia.

En muista onko niitä toistaiseksi mistään muualta lähteestä tulossa osapuolitauluun, mutta parempi varmistaa, että dvv-skripti koskee *vain* niihin osapuoliin, joissa "tiedontuottaja_tunnus" on dvv.

2023-04-12 14:50 UTC, Rikuoja commented on scripts/import_dvv.sql
> +on conflict (osapuoli_id) do update
Tajusin juuri että tämä vaatii kaiketi myös tietokantamigraation :)

Eli tällä hetkellä tietokannassa osapuoli voi olla vanhin asukas vain yhdessä huoneistossa, rakennuksen_vanhimmat-taulun primary key on pelkkä osapuoli_id.

Tämä pitäisi muuttaa niin, että sama henkilö voi asua eri aikoina eri huoneistoissa ja rakennuksissa. Eli käytännössä primary keyn pitäisi olla sitten varmaankin kaikki viisi saraketta
(rakennus_id, osapuoli_id, huoneistokirjain, huoneistonumero, jakokirjain), mutta silloinkin ongelma olisi tapaus, jossa sama henkilö muuttaa takaisin asuntoon jossa on asunut aiemmin.

Eli hmm, nyt alkaa näyttää siltä että pitää tehdä rakennuksen_vanhimmat-tauluun ihan oma id-primary key, jotta näitä vanhimpia voi lisätä. Eli sen jälkeen tätä konfliktia ei enää tule, vaan päivämäärien päivitys pitää hoitaa vain tuolla triggerillä.

Muita kenttiä ei päivitetä, vaan aina jos osapuoli muuttaa vaikka samassa talossa eri huoneistoon, vanhaan vanhimmat-riviin lisätään loppupäivämäärä, ja sitten uuteen vanhimmat-riviin (jossa eri huoneistonumero) tulee vain alkupäivämäärä, ja null-loppupäivämäärä.

2023-04-12 14:50 UTC, Rikuoja commented on scripts/import_dvv.sql
> +on conflict (osapuoli_id) do update
Ja samasta teemasta: koska nyt omistajuudella on myös alku- ja loppupäivämäärä, tajusin että myös rakennuksen_omistajat-tauluun pitänee lisätä id ja poistaa vanha primary key (rakennus_id, osapuoli_id). Tämä sen takia, että sama henkilö voi myydä osuutensa rakennuksesta, ja seuraavana vuonna vaikka ostaa sen takaisin itselleen. Eli omistaja voi kadota yhtenä vuonna ja sen jälkeen ilmestyä takaisin.

2023-10-13 06:39 UTC, ismogis commented on db/Lahti_jkr_db_model_codelists 2023_05_10.png
Todettu jo aiemmin, että halutaan.

2023-10-13 06:41 UTC, merged